import type { IntroTourStepConfig } from "../../lib/introOnboarding";

export const INTRO_TOUR_STEPS: IntroTourStepConfig[] = [
  {
    id: "dashboard",
    title: "Start with the dashboard",
    body: "This is the main workspace for readiness, alerts, evidence quality, and the next best move.",
    targetSelector: '[data-intro-target="dashboard-overview"]',
    fallbackSelector: ".app-detail__header",
    placement: "bottom",
    skipIfTargetMissing: false,
  },
  {
    id: "profile",
    title: "Keep your profile current",
    body: "Profile details help the system personalize names, context, and communication more clearly.",
    targetSelector: '[data-intro-target="account-profile"]',
    fallbackSelector: ".account-menu__trigger",
    placement: "bottom",
    skipIfTargetMissing: false,
  },
  {
    id: "curriculum",
    title: "Review degree requirements",
    body: "Curriculum information should be reviewed visually because scoring depends on accurate degree requirements.",
    targetSelector: '[data-intro-target="curriculum-review"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "top",
    skipIfTargetMissing: true,
  },
  {
    id: "scoring",
    title: "Read the scoring area carefully",
    body: "The readiness score turns available evidence into a clearer picture of progress, gaps, and confidence.",
    targetSelector: '[data-intro-target="readiness-score"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "top",
    skipIfTargetMissing: true,
  },
  {
    id: "actions",
    title: "Turn insight into action",
    body: "Action and recommendation sections translate the current picture into practical next steps.",
    targetSelector: '[data-intro-target="next-actions"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "top",
    skipIfTargetMissing: true,
  },
  {
    id: "communication",
    title: "Use communication tools from their own area",
    body: "Messages and chatbot tools now live in their own left-navigation area so they are easier to find when you need them.",
    targetSelector: '[data-intro-target="nav-communication"]',
    fallbackSelector: '[data-intro-target="nav-open"]',
    placement: "right",
    skipIfTargetMissing: false,
  },
  {
    id: "help",
    title: "Come back to Help anytime",
    body: "Help explains key features, where things live, and lets you replay this intro later whenever you want a refresher.",
    targetSelector: '[data-intro-target="help"]',
    fallbackSelector: ".app-topbar",
    placement: "left",
    skipIfTargetMissing: false,
  },
];
