import type { IntroTourStepConfig } from "../../lib/introOnboarding";

export const INTRO_TOUR_STEPS: IntroTourStepConfig[] = [
  {
    id: "workspace-home",
    title: "Start in the workspace",
    body: "Rising Senior opens into a shared workspace shell with a dashboard, guided navigation, and a detail panel for the work you are doing now.",
    targetSelector: '[data-intro-target="dashboard-overview"]',
    fallbackSelector: ".app-detail__header",
    placement: "bottom",
    skipIfTargetMissing: false,
  },
  {
    id: "navigation",
    title: "Use the left navigation as your map",
    body: "The left column organizes the main areas: workspace, profile, household setup, academic path, documents, Career Goal, communication, and help.",
    targetSelector: '[data-intro-target="nav-workspace"]',
    fallbackSelector: '[data-intro-target="nav-open"]',
    placement: "right",
    skipIfTargetMissing: false,
  },
  {
    id: "profile",
    title: "Keep profile details current",
    body: "Profile settings keep names, communication preferences, and optional personal context accurate so the system can speak clearly and respectfully.",
    targetSelector: '[data-intro-target="account-profile"]',
    fallbackSelector: '[data-intro-target="nav-profile"]',
    placement: "bottom",
    skipIfTargetMissing: false,
  },
  {
    id: "household",
    title: "Accounts eventually connect through a household",
    body: "The system is designed around a household that centers on a student and can include a parent or guardian plus an optional coach. Signup, invitations, and access requests already use that model today, and later enrollment can add more detail without changing the underlying relationship structure.",
    targetSelector: '[data-intro-target="nav-household"]',
    fallbackSelector: '[data-intro-target="nav-profile"]',
    placement: "right",
    skipIfTargetMissing: false,
  },
  {
    id: "academic-path",
    title: "Academic path and evidence shape the context",
    body: "School, major, documents, academic evidence, and curriculum verification all help the platform explain fit, gaps, and next steps with more confidence.",
    targetSelector: '[data-intro-target="nav-onboarding"]',
    fallbackSelector: '[data-intro-target="academic-evidence"]',
    placement: "right",
    skipIfTargetMissing: true,
  },
  {
    id: "career-goal",
    title: "Career Goal turns a real target into a working plan",
    body: "Career Goal lets you paste a job description, save multiple named goals, compare them, and see job-specific readiness guidance without overwriting the baseline student record.",
    targetSelector: '[data-intro-target="nav-career-goal"]',
    fallbackSelector: '[data-intro-target="active-career-goal"]',
    placement: "right",
    skipIfTargetMissing: false,
  },
  {
    id: "communication-help",
    title: "Communication and Help stay close by",
    body: "Messages & chat is where communication tools live, and Help explains how the platform works, how to replay these tours, and what to do next.",
    targetSelector: '[data-intro-target="nav-communication"]',
    fallbackSelector: '[data-intro-target="help"]',
    placement: "right",
    skipIfTargetMissing: false,
  },
];

export const ROLE_INTRO_TOUR_STEPS: IntroTourStepConfig[] = [
  {
    id: "student-dashboard",
    title: "Student dashboard centers strategy and readiness",
    body: "Use the student dashboard to review the current readiness picture, the strongest evidence on file, and the next move worth taking now.",
    targetSelector: '[data-intro-target="dashboard-overview"]',
    fallbackSelector: '[data-intro-target="readiness-score"]',
    placement: "bottom",
    rolesAllowed: ["student"],
    skipIfTargetMissing: false,
  },
  {
    id: "student-onboarding",
    title: "Student onboarding sets the academic path",
    body: "Academic path, career interests, deadlines, and communication preferences give the dashboard the context it needs to guide the student well.",
    targetSelector: '[data-intro-target="nav-onboarding"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "right",
    rolesAllowed: ["student"],
    skipIfTargetMissing: true,
  },
  {
    id: "student-documents",
    title: "Student documents and evidence matter",
    body: "Uploads, transcript evidence, and degree requirement files are how the system proves what is already on file instead of guessing.",
    targetSelector: '[data-intro-target="nav-documents"]',
    fallbackSelector: '[data-intro-target="academic-evidence"]',
    placement: "right",
    rolesAllowed: ["student"],
    skipIfTargetMissing: true,
  },
  {
    id: "student-score",
    title: "Student scoring depends on verified evidence",
    body: "The readiness score becomes more trustworthy when curriculum and academic evidence are complete, reviewed, and tied to a clear target.",
    targetSelector: '[data-intro-target="readiness-score"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "top",
    rolesAllowed: ["student"],
    skipIfTargetMissing: true,
  },
  {
    id: "student-actions",
    title: "Student next actions turn insight into progress",
    body: "Next steps, outcomes, and Career Goal guidance are where the platform turns the current picture into a short, practical plan.",
    targetSelector: '[data-intro-target="next-actions"]',
    fallbackSelector: '[data-intro-target="nav-career-goal"]',
    placement: "top",
    rolesAllowed: ["student"],
    skipIfTargetMissing: true,
  },
  {
    id: "student-career-goal",
    title: "Student Career Goal keeps multiple options alive",
    body: "Use Career Goal when the student wants to compare multiple job directions side by side without losing the general dashboard baseline.",
    targetSelector: '[data-intro-target="nav-career-goal"]',
    fallbackSelector: '[data-intro-target="active-career-goal"]',
    placement: "right",
    rolesAllowed: ["student"],
    skipIfTargetMissing: false,
  },
  {
    id: "parent-dashboard",
    title: "Parent dashboard is family-facing, not surveillance",
    body: "The parent dashboard summarizes what matters most, what support is useful now, and what the family can act on without overwhelming the student.",
    targetSelector: '[data-intro-target="dashboard-overview"]',
    fallbackSelector: '[data-intro-target="nav-parent-dashboard"]',
    placement: "bottom",
    rolesAllowed: ["parent"],
    skipIfTargetMissing: false,
  },
  {
    id: "parent-onboarding",
    title: "Parent onboarding sets the communication baseline",
    body: "Parent onboarding captures family communication preferences, concerns, and the tone that should guide parent-facing support.",
    targetSelector: '[data-intro-target="nav-parent-onboarding"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "right",
    rolesAllowed: ["parent"],
    skipIfTargetMissing: true,
  },
  {
    id: "parent-actions",
    title: "Parent actions highlight where support helps most",
    body: "Use the next actions area to see where the student may need family help, what is urgent, and what should stay student-led.",
    targetSelector: '[data-intro-target="next-actions"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "top",
    rolesAllowed: ["parent"],
    skipIfTargetMissing: true,
  },
  {
    id: "parent-history",
    title: "Parent history keeps prior context visible",
    body: "History helps the family revisit earlier updates, messages, and context without rebuilding the timeline from memory.",
    targetSelector: '[data-intro-target="nav-parent-history"]',
    fallbackSelector: '[data-intro-target="nav-parent-dashboard"]',
    placement: "right",
    rolesAllowed: ["parent"],
    skipIfTargetMissing: true,
  },
  {
    id: "parent-communication",
    title: "Parent communication tools live in their own area",
    body: "Messages & chat keeps translated communication, shared context, and parent-safe message drafting in one consistent place.",
    targetSelector: '[data-intro-target="nav-communication"]',
    fallbackSelector: '[data-intro-target="help"]',
    placement: "right",
    rolesAllowed: ["parent"],
    skipIfTargetMissing: false,
  },
  {
    id: "parent-career-goal",
    title: "Parent Career Goal shows job-specific context",
    body: "Parents can review the active Career Goal to understand how major, evidence, and missing pieces affect a concrete career target.",
    targetSelector: '[data-intro-target="nav-career-goal"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "right",
    rolesAllowed: ["parent"],
    skipIfTargetMissing: false,
  },
  {
    id: "coach-dashboard",
    title: "Coach dashboard is organized around the selected student",
    body: "The coach workspace keeps the current student, readiness picture, evidence quality, and follow-up workflow together in one review surface.",
    targetSelector: '[data-intro-target="dashboard-overview"]',
    fallbackSelector: '[data-intro-target="nav-coach-dashboard"]',
    placement: "bottom",
    rolesAllowed: ["coach"],
    skipIfTargetMissing: false,
  },
  {
    id: "coach-roster",
    title: "Coach roster controls who the workspace is about",
    body: "The roster is how coaches stay inside assigned-student boundaries. Switching students here should never leak another student’s context into view.",
    targetSelector: '[data-intro-target="coach-roster"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "bottom",
    rolesAllowed: ["coach"],
    skipIfTargetMissing: true,
  },
  {
    id: "coach-score",
    title: "Coach scoring and evidence highlight where support matters",
    body: "Use the score and evidence areas to decide whether the student needs stronger academic proof, clearer targets, or faster action on missing pieces.",
    targetSelector: '[data-intro-target="readiness-score"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "top",
    rolesAllowed: ["coach"],
    skipIfTargetMissing: true,
  },
  {
    id: "coach-curriculum",
    title: "Coach curriculum review flags confidence limits",
    body: "Degree requirements still need review even in coach view, because curriculum quality changes how much confidence the platform can place in academic scoring.",
    targetSelector: '[data-intro-target="curriculum-review"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "top",
    rolesAllowed: ["coach"],
    skipIfTargetMissing: true,
  },
  {
    id: "coach-actions",
    title: "Coach actions turn review into follow-up",
    body: "Notes, recommendations, action items, flags, and outreach all live in the next-actions workflow so coaching decisions turn into visible follow-up.",
    targetSelector: '[data-intro-target="next-actions"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "top",
    rolesAllowed: ["coach"],
    skipIfTargetMissing: true,
  },
  {
    id: "coach-career-goal",
    title: "Coach Career Goal keeps job-target work student-specific",
    body: "Career Goal lets a coach compare exact job targets for the selected student without leaking scenarios across the roster.",
    targetSelector: '[data-intro-target="nav-career-goal"]',
    fallbackSelector: '[data-intro-target="dashboard-overview"]',
    placement: "right",
    rolesAllowed: ["coach"],
    skipIfTargetMissing: false,
  },
];
